server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: execution-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trading}
    username: ${DB_USER:trading}
    password: ${DB_PASSWORD:trading}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: execution_svc
  flyway:
    schemas: execution_svc
    create-schemas: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

management:
  metrics:
    tags:
      application: execution-service
  endpoints.web.exposure.include: health,info,prometheus
